import { type NextRequest, NextResponse } from "next/server";
import axios from "axios";
import * as cheerio from "cheerio";

// Your existing helper functions remain the same
function generateSummary(content: string): string {
  const sentences = content.match(/[^.!?\n]+[.!?]?/g) || [];
  const uniqueSentences = Array.from(
    new Set(sentences.map((s) => s.trim()))
  ).filter(
    (s) =>
      s.length > 30 &&
      !s.match(
        /placeholder|no-script|Business Insider tells the innovative stories you want to know/i
      )
  );
  return uniqueSentences.slice(0, 3).join(" ") || "";
}

const translationDict: Record<string, string> = {
  the: "یہ",
  is: "ہے",
  a: "ایک",
  an: "ایک",
  and: "اور",
  or: "یا",
  but: "لیکن",
  in: "میں",
  on: "پر",
  at: "میں",
  to: "کو",
  for: "کے لیے",
  of: "کا",
  with: "کے ساتھ",
  by: "سے",
  from: "سے",
  up: "اوپر",
  about: "کے بارے میں",
  into: "میں",
  through: "کے ذریعے",
  during: "کے دوران",
  before: "پہلے",
  after: "بعد",
  above: "اوپر",
  below: "نیچے",
  between: "کے درمیان",
  this: "یہ",
  that: "وہ",
  these: "یہ",
  those: "وہ",
  article: "مضمون",
  blog: "بلاگ",
  content: "مواد",
  information: "معلومات",
  technology: "ٹیکنالوجی",
  development: "ترقی",
  business: "کاروبار",
  market: "بازار",
  company: "کمپنی",
  product: "پروڈکٹ",
  service: "خدمت",
  customer: "گاہک",
  user: "صارف",
  system: "نظام",
  data: "ڈیٹا",
  analysis: "تجزیہ",
  research: "تحقیق",
  study: "مطالعہ",
  report: "رپورٹ",
  news: "خبریں",
  update: "اپڈیٹ",
  new: "نیا",
  old: "پرانا",
  good: "اچھا",
  bad: "برا",
  important: "اہم",
  significant: "اہم",
  major: "بڑا",
  minor: "چھوٹا",
  recent: "حالیہ",
  current: "موجودہ",
  future: "مستقبل",
  past: "ماضی",
  today: "آج",
  tomorrow: "کل",
  yesterday: "کل",
  week: "ہفتہ",
  month: "مہینہ",
  year: "سال",
  time: "وقت",
  work: "کام",
  team: "ٹیم",
  project: "منصوبہ",
  solution: "حل",
  problem: "مسئلہ",
  issue: "مسئلہ",
  challenge: "چیلنج",
  opportunity: "موقع",
  success: "کامیابی",
  failure: "ناکامی",
  growth: "اضافہ",
  change: "تبدیلی",
  improve: "بہتر",
  increase: "اضافہ",
  decrease: "کمی",
  help: "مدد",
  support: "سپورٹ",
  provide: "فراہم",
  offer: "پیش",
  create: "بنانا",
  build: "بنانا",
  develop: "ترقی",
  design: "ڈیزائن",
  manage: "منظم",
  control: "کنٹرول",
  process: "عمل",
  method: "طریقہ",
  approach: "نقطہ نظر",
  strategy: "حکمت عملی",
  plan: "منصوبہ",
  goal: "مقصد",
  objective: "مقصد",
  target: "ہدف",
  result: "نتیجہ",
  outcome: "نتیجہ",
  benefit: "فائدہ",
  advantage: "فائدہ",
  feature: "خصوصیت",
  function: "فنکشن",
  performance: "کارکردگی",
  quality: "معیار",
  value: "قیمت",
  cost: "لاگت",
  price: "قیمت",
  money: "پیسہ",
  investment: "سرمایہ",
  revenue: "آمدنی",
  profit: "منافع",
  loss: "نقصان",
  risk: "خطرہ",
  security: "سیکیورٹی",
  safety: "حفاظت",
  protection: "تحفظ",
  privacy: "رازداری",
  public: "عوامی",
  private: "نجی",
  personal: "ذاتی",
  professional: "پیشہ ورانہ",
  social: "سماجی",
  economic: "اقتصادی",
  political: "سیاسی",
  cultural: "ثقافتی",
  educational: "تعلیمی",
  medical: "طبی",
  health: "صحت",
  environment: "ماحول",
  energy: "توانائی",
  power: "طاقت",
  network: "نیٹ ورک",
  internet: "انٹرنیٹ",
  website: "ویب سائٹ",
  application: "ایپلیکیشن",
  software: "سافٹ ویئر",
  hardware: "ہارڈ ویئر",
  computer: "کمپیوٹر",
  mobile: "موبائل",
  device: "آلہ",
  tool: "آلہ",
  platform: "پلیٹ فارم",
  framework: "فریم ورک",
  library: "لائبریری",
  database: "ڈیٹابیس",
  server: "سرور",
  client: "کلائنٹ",
  interface: "انٹرفیس",
  experience: "تجربہ",
  knowledge: "علم",
  skill: "مہارت",
  ability: "صلاحیت",
  capacity: "گنجائش",
  resource: "وسائل",
  material: "مواد",
  text: "متن",
  image: "تصویر",
  video: "ویڈیو",
  audio: "آڈیو",
  file: "فائل",
  document: "دستاویز",
  page: "صفحہ",
  section: "حصہ",
  part: "حصہ",
  chapter: "باب",
  topic: "موضوع",
  subject: "موضوع",
  title: "عنوان",
  name: "نام",
  description: "تفصیل",
  detail: "تفصیل",
  summary: "خلاصہ",
  overview: "جائزہ",
  introduction: "تعارف",
  conclusion: "نتیجہ",
  recommendation: "سفارش",
  suggestion: "تجویز",
  advice: "مشورہ",
  tip: "ٹپ",
  guide: "گائیڈ",
  tutorial: "ٹیوٹوریل",
  example: "مثال",
  case: "کیس",
  scenario: "منظرنامہ",
  situation: "صورتحال",
  condition: "شرط",
  requirement: "ضرورت",
  specification: "تفصیلات",
  standard: "معیار",
  rule: "اصول",
  policy: "پالیسی",
  procedure: "طریقہ کار",
  step: "قدم",
  stage: "مرحلہ",
  phase: "مرحلہ",
  level: "سطح",
  degree: "درجہ",
  scale: "پیمانہ",
  size: "سائز",
  amount: "مقدار",
  number: "نمبر",
  count: "شمار",
  total: "کل",
  sum: "مجموعہ",
  average: "اوسط",
  rate: "شرح",
  percentage: "فیصد",
  ratio: "تناسب",
  comparison: "موازنہ",
  difference: "فرق",
  similarity: "مماثلت",
  relation: "تعلق",
  connection: "رابطہ",
  link: "لنک",
  reference: "حوالہ",
  source: "ذریعہ",
  origin: "اصل",
  base: "بنیاد",
  foundation: "بنیاد",
  structure: "ڈھانچہ",
  organization: "تنظیم",
  arrangement: "ترتیب",
  order: "ترتیب",
  sequence: "تسلسل",
  series: "سلسلہ",
  list: "فہرست",
  item: "آئٹم",
  element: "عنصر",
  component: "جزو",
  factor: "عنصر",
  aspect: "پہلو",
  characteristic: "خصوصیت",
  property: "خاصیت",
  attribute: "خاصیت",
  variable: "متغیر",
  parameter: "پیرامیٹر",
  option: "اختیار",
  choice: "انتخاب",
  decision: "فیصلہ",
  selection: "انتخاب",
  preference: "ترجیح",
  priority: "ترجیح",
  importance: "اہمیت",
  significance: "اہمیت",
  relevance: "متعلقہ",
  impact: "اثر",
  effect: "اثر",
  influence: "اثر",
  consequence: "نتیجہ",
  implication: "مطلب",
  meaning: "مطلب",
  purpose: "مقصد",
  intention: "ارادہ",
  aim: "مقصد",
  mission: "مشن",
  vision: "نظریہ",
  concept: "تصور",
  idea: "خیال",
  thought: "خیال",
  opinion: "رائے",
  view: "نظریہ",
  perspective: "نقطہ نظر",
  angle: "زاویہ",
  point: "نکتہ",
  position: "پوزیشن",
  location: "مقام",
  place: "جگہ",
  area: "علاقہ",
  region: "علاقہ",
  zone: "زون",
  field: "فیلڈ",
  domain: "ڈومین",
  sector: "سیکٹر",
  industry: "صنعت",
  economy: "معیشت",
  finance: "مالیات",
  budget: "بجٹ",
  funding: "فنڈنگ",
  capital: "سرمایہ",
  asset: "اثاثہ",
  liability: "ذمہ داری",
  debt: "قرض",
  credit: "کریڈٹ",
  loan: "قرض",
  payment: "ادائیگی",
  transaction: "لین دین",
  exchange: "تبادلہ",
  trade: "تجارت",
  commerce: "تجارت",
  sales: "فروخت",
  purchase: "خریداری",
  buy: "خریدنا",
  sell: "بیچنا",
  deal: "ڈیل",
  contract: "معاہدہ",
  agreement: "معاہدہ",
  terms: "شرائط",
  conditions: "شرائط",
  clause: "شق",
  provision: "فراہمی",
  supply: "سپلائی",
  demand: "مانگ",
  need: "ضرورت",
  want: "چاہنا",
  desire: "خواہش",
  wish: "خواہش",
  hope: "امید",
  expectation: "توقع",
  assumption: "قیاس",
  hypothesis: "قیاس",
  theory: "نظریہ",
  model: "ماڈل",
  pattern: "پیٹرن",
  trend: "رجحان",
  direction: "سمت",
  path: "راستہ",
  route: "راستہ",
  way: "طریقہ",
  means: "ذریعہ",
  mechanism: "طریقہ کار",
  technique: "تکنیک",
  talent: "صلاحیت",
  gift: "تحفہ",
  capability: "صلاحیت",
  potential: "صلاحیت",
  strength: "طاقت",
  weakness: "کمزوری",
  disadvantage: "نقصان",
  harm: "نقصان",
  damage: "نقصان",
  injury: "چوٹ",
  hurt: "تکلیف",
  pain: "درد",
  pleasure: "خوشی",
  happiness: "خوشی",
  joy: "خوشی",
  satisfaction: "اطمینان",
  peace: "امن",
  calm: "پرسکون",
  quiet: "خاموش",
  silent: "خاموش",
  noise: "شور",
  sound: "آواز",
  voice: "آواز",
  speech: "تقریر",
  language: "زبان",
  word: "لفظ",
  term: "اصطلاح",
  phrase: "جملہ",
  sentence: "جملہ",
  paragraph: "پیراگراف",
  story: "کہانی",
  tale: "کہانی",
  narrative: "بیان",
  account: "اکاؤنٹ",
  record: "ریکارڈ",
  log: "لاگ",
  entry: "اندراج",
  note: "نوٹ",
  comment: "تبصرہ",
  remark: "تبصرہ",
  observation: "مشاہدہ",
  notice: "نوٹس",
  attention: "توجہ",
  focus: "توجہ",
  concentration: "توجہ",
  effort: "کوشش",
  attempt: "کوشش",
  try: "کوشش",
  trial: "آزمائش",
  test: "ٹیسٹ",
  exam: "امتحان",
  assessment: "تشخیص",
  evaluation: "تشخیص",
  judgment: "فیصلہ",
  belief: "عقیدہ",
  faith: "ایمان",
  trust: "اعتماد",
  confidence: "اعتماد",
  certainty: "یقین",
  doubt: "شک",
  question: "سوال",
  answer: "جواب",
  response: "جواب",
  reply: "جواب",
  reaction: "ردعمل",
  action: "عمل",
  activity: "سرگرمی",
  behavior: "رفتار",
  conduct: "رفتار",
  attitude: "رویہ",
  style: "انداز",
  manner: "طریقہ",
  fashion: "انداز",
  mode: "موڈ",
  form: "شکل",
  shape: "شکل",
  appearance: "ظاہری شکل",
  look: "نظر",
  sight: "نظر",
  scene: "منظر",
  picture: "تصویر",
  photo: "فوٹو",
  illustration: "مثال",
  diagram: "خاکہ",
  chart: "چارٹ",
  graph: "گراف",
  table: "جدول",
  figure: "شکل",
  digit: "ہندسہ",
  code: "کوڈ",
  symbol: "علامت",
  sign: "نشان",
  mark: "نشان",
  label: "لیبل",
  tag: "ٹیگ",
  category: "کیٹگری",
  class: "کلاس",
  type: "قسم",
  kind: "قسم",
  sort: "قسم",
  variety: "قسم",
  version: "ورژن",
  edition: "ایڈیشن",
  release: "ریلیز",
  upgrade: "اپگریڈ",
  improvement: "بہتری",
  enhancement: "بہتری",
  modification: "تبدیلی",
  alteration: "تبدیلی",
  adjustment: "ایڈجسٹمنٹ",
  correction: "اصلاح",
  fix: "ٹھیک کرنا",
  repair: "مرمت",
  maintenance: "دیکھ بھال",
  care: "دیکھ بھال",
  assistance: "مدد",
  aid: "مدد",
  relief: "ریلیف",
  rescue: "بچاؤ",
  save: "بچانا",
  protect: "تحفظ",
  defend: "دفاع",
  guard: "محافظ",
  watch: "دیکھنا",
  monitor: "مانیٹر",
  observe: "مشاہدہ",
  check: "چیک",
  verify: "تصدیق",
  confirm: "تصدیق",
  validate: "تصدیق",
  approve: "منظوری",
  accept: "قبول",
  agree: "متفق",
  consent: "رضامندی",
  permission: "اجازت",
  license: "لائسنس",
  permit: "اجازت",
  allow: "اجازت دینا",
  enable: "فعال",
  disable: "غیر فعال",
  activate: "فعال",
  deactivate: "غیر فعال",
  start: "شروع",
  begin: "شروع",
  commence: "شروع",
  initiate: "شروع",
  launch: "لانچ",
  open: "کھولنا",
  close: "بند",
  end: "ختم",
  finish: "ختم",
  complete: "مکمل",
  conclude: "نتیجہ",
  stop: "رک جانا",
  pause: "رک جانا",
  break: "وقفہ",
  rest: "آرام",
  sleep: "سونا",
  wake: "جاگنا",
  rise: "اٹھنا",
  stand: "کھڑا",
  sit: "بیٹھنا",
  lie: "لیٹنا",
  walk: "چلنا",
  run: "دوڑنا",
  move: "حرکت",
  go: "جانا",
  come: "آنا",
  arrive: "پہنچنا",
  reach: "پہنچنا",
  leave: "چھوڑنا",
  depart: "روانہ",
  return: "واپس",
  back: "پیچھے",
  forward: "آگے",
  ahead: "آگے",
  behind: "پیچھے",
  next: "اگلا",
  previous: "پچھلا",
  last: "آخری",
  first: "پہلا",
  second: "دوسرا",
  third: "تیسرا",
  final: "حتمی",
  initial: "ابتدائی",
  original: "اصل",
  copy: "کاپی",
  duplicate: "نقل",
  replica: "نقل",
  variant: "متغیر",
  alternative: "متبادل",
  possibility: "امکان",
  chance: "موقع",
  occasion: "موقع",
  event: "واقعہ",
  incident: "واقعہ",
  occurrence: "واقعہ",
  happening: "ہونا",
  progress: "ترقی",
  advancement: "ترقی",
  evolution: "ارتقاء",
  revolution: "انقلاب",
  transformation: "تبدیلی",
  conversion: "تبدیلی",
  transition: "منتقلی",
  shift: "تبدیلی",
  switch: "سوئچ",
  swap: "تبدیل",
  replace: "بدلنا",
  substitute: "متبادل",
  backup: "بیک اپ",
  reserve: "ریزرو",
  spare: "اضافی",
  extra: "اضافی",
  additional: "اضافی",
  more: "زیادہ",
  less: "کم",
  few: "کم",
  many: "زیادہ",
  several: "کئی",
  some: "کچھ",
  any: "کوئی",
  all: "تمام",
  every: "ہر",
  each: "ہر ایک",
  both: "دونوں",
  either: "یا تو",
  neither: "نہ تو",
  none: "کوئی نہیں",
  nothing: "کچھ نہیں",
  something: "کچھ",
  anything: "کچھ بھی",
  everything: "سب کچھ",
  everyone: "ہر کوئی",
  someone: "کوئی",
  anyone: "کوئی بھی",
  "no one": "کوئی نہیں",
  nobody: "کوئی نہیں",
  somebody: "کوئی",
  anybody: "کوئی بھی",
  everybody: "ہر کوئی",
  person: "شخص",
  people: "لوگ",
  individual: "فرد",
  group: "گروپ",
  enterprise: "ادارہ",
  institution: "ادارہ",
  agency: "ایجنسی",
  department: "شعبہ",
  division: "ڈویژن",
  unit: "یونٹ",
  branch: "برانچ",
  office: "دفتر",
  headquarters: "صدر دفتر",
  building: "عمارت",
  facility: "سہولت",
  center: "مرکز",
  hub: "مرکز",
  station: "اسٹیشن",
  site: "سائٹ",
  address: "پتہ",
  contact: "رابطہ",
  phone: "فون",
  email: "ای میل",
  message: "پیغام",
  communication: "ابلاغ",
  conversation: "بات چیت",
  discussion: "بحث",
  meeting: "ملاقات",
  conference: "کانفرنس",
  session: "سیشن",
  workshop: "ورکشاپ",
  seminar: "سیمینار",
  training: "تربیت",
  education: "تعلیم",
  learning: "سیکھنا",
  teaching: "پڑھانا",
  instruction: "ہدایت",
  guidance: "رہنمائی",
  leadership: "قیادت",
  management: "انتظام",
  administration: "انتظامیہ",
  government: "حکومت",
  authority: "اختیار",
  command: "کمانڈ",
  request: "درخواست",
  necessity: "ضرورت",
  essential: "ضروری",
  critical: "انتہائی اہم",
  vital: "بہت اہم",
  crucial: "انتہائی اہم",
  key: "اہم",
  main: "اہم",
  primary: "بنیادی",
  secondary: "ثانوی",
  basic: "بنیادی",
  fundamental: "بنیادی",
  core: "بنیادی",
  central: "مرکزی",
  general: "عام",
  specific: "مخصوص",
  particular: "خاص",
  special: "خاص",
  unique: "منفرد",
  common: "عام",
  normal: "عام",
  regular: "باقاعدہ",
  usual: "عام",
  typical: "عام",
  ordinary: "عام",
  simple: "آسان",
  easy: "آسان",
  difficult: "مشکل",
  hard: "مشکل",
  complex: "پیچیدہ",
  complicated: "پیچیدہ",
  advanced: "ایڈوانس",
  sophisticated: "نفیس",
  modern: "جدید",
  contemporary: "جدید",
  latest: "تازہ ترین",
  fresh: "تازہ",
  novel: "نیا",
  innovative: "اختراعی",
  creative: "تخلیقی",
  traditional: "روایتی",
  conventional: "روایتی",
  classic: "کلاسک",
  vintage: "پرانا",
  antique: "قدیم",
  ancient: "قدیم",
  historic: "تاریخی",
  historical: "تاریخی",
  former: "سابقہ",
  ex: "سابقہ",
  aged: "بوڑھا",
  mature: "بالغ",
  adult: "بالغ",
  young: "جوان",
  junior: "جونیئر",
  senior: "سینئر",
  elder: "بزرگ",
  child: "بچہ",
  kid: "بچہ",
  baby: "بچہ",
  infant: "شیر خوار",
  teenager: "نوجوان",
  youth: "نوجوان",
  student: "طالب علم",
  pupil: "شاگرد",
  scholar: "عالم",
  expert: "ماہر",
  specialist: "ماہر",
  amateur: "شوقیہ",
  beginner: "ابتدائی",
  novice: "نیا",
  experienced: "تجربہ کار",
  skilled: "ماہر",
  talented: "باصلاحیت",
  gifted: "قابل",
  capable: "قابل",
  competent: "قابل",
  qualified: "اہل",
  certified: "تصدیق شدہ",
  licensed: "لائسنس یافتہ",
  authorized: "مجاز",
  approved: "منظور شدہ",
  official: "سرکاری",
  formal: "رسمی",
  informal: "غیر رسمی",
  casual: "عام",
  serious: "سنجیدہ",
  strict: "سخت",
  flexible: "لچکدار",
  rigid: "سخت",
  fixed: "مقرر",
  stable: "مستحکم",
  steady: "مستحکم",
  constant: "مستقل",
  consistent: "مستقل",
  reliable: "قابل اعتماد",
  dependable: "قابل اعتماد",
  trustworthy: "قابل اعتماد",
  honest: "ایمان دار",
  true: "سچ",
  false: "جھوٹ",
  correct: "درست",
  wrong: "غلط",
  right: "درست",
  accurate: "درست",
  precise: "درست",
  exact: "بالکل",
  perfect: "کامل",
  full: "مکمل",
  partial: "جزوی",
  incomplete: "نامکمل",
  empty: "خالی",
  blank: "خالی",
  clear: "صاف",
  clean: "صاف",
  dirty: "گندا",
  pure: "خالص",
  mixed: "ملا ہوا",
  combined: "ملا ہوا",
  separate: "الگ",
  single: "واحد",
  multiple: "متعدد",
  double: "دوہرا",
  triple: "تین گنا",
  half: "آدھا",
  quarter: "چوتھائی",
  whole: "پورا",
  entire: "مکمل",
  addition: "اضافہ",
  subtraction: "تفریق",
  multiplication: "ضرب",
  calculation: "حساب",
  mathematics: "ریاضی",
  science: "سائنس",
  physics: "طبیعیات",
  chemistry: "کیمسٹری",
  biology: "حیاتیات",
  medicine: "طب",
  fitness: "تندرستی",
  exercise: "ورزش",
  sport: "کھیل",
  game: "کھیل",
  play: "کھیلنا",
  fun: "مزہ",
  entertainment: "تفریح",
  hobby: "شوق",
  interest: "دلچسپی",
  passion: "جنون",
  love: "محبت",
  like: "پسند",
  enjoy: "لطف اندوز",
  prefer: "ترجیح",
  choose: "انتخاب",
  select: "منتخب",
  pick: "چننا",
  decide: "فیصلہ",
  determine: "طے کرنا",
  resolve: "حل کرنا",
  solve: "حل کرنا",
  matter: "معاملہ",
  state: "حالت",
  status: "حالت",
  rank: "درجہ",
  grade: "درجہ",
  score: "اسکور",
  reason: "وجہ",
  cause: "وجہ",
  force: "طاقت",
  job: "نوکری",
  task: "کام",
  duty: "فرض",
  responsibility: "ذمہ داری",
  obligation: "فرض",
  commitment: "عہد",
  promise: "وعدہ",
  guarantee: "ضمانت",
  assurance: "یقین",
  respect: "احترام",
  honor: "عزت",
  dignity: "وقار",
  pride: "فخر",
  shame: "شرم",
  guilt: "جرم",
  blame: "الزام",
  fault: "خرابی",
  mistake: "غلطی",
  error: "خرابی",
  achievement: "کامیابی",
  accomplishment: "کامیابی",
  victory: "فتح",
  win: "جیت",
  lose: "ہار",
  defeat: "شکست",
  competition: "مقابلہ",
  contest: "مقابلہ",
  race: "دوڑ",
  match: "میچ",
  tournament: "ٹورنامنٹ",
  championship: "چیمپئن شپ",
  league: "لیگ",
  player: "کھلاڑی",
  member: "رکن",
  participant: "شرکت کنندہ",
  candidate: "امیدوار",
  applicant: "درخواست گزار",
  volunteer: "رضاکار",
  helper: "مددگار",
  assistant: "اسسٹنٹ",
  supporter: "حامی",
  fan: "مداح",
  follower: "پیروکار",
  leader: "رہنما",
  manager: "منیجر",
  director: "ڈائریکٹر",
  chief: "چیف",
  head: "سربراہ",
  boss: "باس",
  supervisor: "نگران",
  coordinator: "کوآرڈینیٹر",
  organizer: "منتظم",
  planner: "منصوبہ ساز",
  designer: "ڈیزائنر",
  developer: "ڈیولپر",
  programmer: "پروگرامر",
  engineer: "انجینئر",
  technician: "تکنیکی ماہر",
  operator: "آپریٹر",
  visitor: "ملاقاتی",
  guest: "مہمان",
  host: "میزبان",
  owner: "مالک",
  seller: "فروخت کنندہ",
  buyer: "خریدار",
  vendor: "فروخت کنندہ",
  supplier: "فراہم کنندہ",
  provider: "فراہم کنندہ",
  manufacturer: "بنانے والا",
  producer: "پیدا کنندہ",
  creator: "تخلیق کار",
  author: "مصنف",
  writer: "لکھاری",
  editor: "ایڈیٹر",
  publisher: "ناشر",
  printer: "پرنٹر",
  reader: "پڑھنے والا",
  viewer: "دیکھنے والا",
  listener: "سننے والا",
  speaker: "بولنے والا",
  teacher: "استاد",
  instructor: "انسٹرکٹر",
  trainer: "ٹرینر",
  coach: "کوچ",
  mentor: "رہنما",
  advisor: "مشیر",
  consultant: "مشیر",
  counselor: "مشیر",
  therapist: "معالج",
  doctor: "ڈاکٹر",
  nurse: "نرس",
  patient: "مریض",
  lawyer: "وکیل",
  judge: "جج",
  police: "پولیس",
  officer: "افسر",
  soldier: "سپاہی",
  pilot: "پائلٹ",
  driver: "ڈرائیور",
  chef: "شیف",
  cook: "باورچی",
  waiter: "ویٹر",
  clerk: "کلرک",
  secretary: "سیکرٹری",
  receptionist: "ریسپشنسٹ",
  accountant: "اکاؤنٹنٹ",
  banker: "بینکر",
  agent: "ایجنٹ",
  broker: "بروکر",
  dealer: "ڈیلر",
  trader: "تاجر",
  merchant: "تاجر",
  businessman: "کاروباری",
  entrepreneur: "کاروباری",
  investor: "سرمایہ کار",
  partner: "پارٹنر",
  colleague: "ساتھی",
  coworker: "ہم کار",
  employee: "ملازم",
  worker: "کارگر",
  staff: "عملہ",
  crew: "عملہ",
  faculty: "فیکلٹی",
  board: "بورڈ",
  committee: "کمیٹی",
  council: "کونسل",
  assembly: "اسمبلی",
  parliament: "پارلیمنٹ",
  ministry: "وزارت",
  bureau: "بیورو",
  commission: "کمیشن",
  association: "انجمن",
  society: "معاشرہ",
  club: "کلب",
  union: "یونین",
  federation: "فیڈریشن",
  alliance: "اتحاد",
  partnership: "شراکت",
  cooperation: "تعاون",
  collaboration: "تعاون",
  coordination: "ہم آہنگی",
  relationship: "رشتہ",
  friendship: "دوستی",
  family: "خاندان",
  relative: "رشتہ دار",
  parent: "والدین",
  sibling: "بہن بھائی",
  spouse: "شریک حیات",
  neighbor: "پڑوسی",
  community: "کمیونٹی",
  citizen: "شہری",
  resident: "رہائشی",
  inhabitant: "باشندہ",
  population: "آبادی",
  crowd: "ہجوم",
  audience: "سامعین",
  spectator: "تماشائی",
  witness: "گواہ",
  observer: "مشاہد",
  contributor: "تعاون کنندہ",
  donor: "عطیہ دہندہ",
  sponsor: "کفیل",
  advocate: "وکیل",
  representative: "نمائندہ",
  delegate: "نمائندہ",
  ambassador: "سفیر",
  diplomat: "سفارت کار",
};

function translateToUrdu(text: string): string {
  return text.replace(/\w+/g, (word) => {
    const cleanWord = word.toLowerCase();
    return translationDict[cleanWord] || word;
  });
}

function extractTextFromHtml(html: string): string {
  const $ = cheerio.load(html);

  $(
    "script, style, nav, header, footer, aside, img, .no-script, .placeholder"
  ).remove();

  const contentSelectors = [
    "article",
    ".post-content",
    ".entry-content",
    ".content",
    "main",
    ".main-content",
    "#content",
    ".post-body",
  ];

  let content = "";
  for (const selector of contentSelectors) {
    const element = $(selector);
    if (element.length > 0) {
      content = element.text();
      break;
    }
  }

  if (!content) {
    content = $("body").text();
  }

  const lines = content
    .replace(/\s+/g, " ")
    .split(/[\r\n]+/)
    .map((line) => line.trim())
    .filter(
      (line) =>
        line.length > 0 &&
        !line.match(
          /placeholder|no-script|Business Insider tells the innovative stories you want to know/i
        )
    );

  const uniqueLines = Array.from(new Set(lines));
  return uniqueLines.join(" ");
}

function calculateReadTime(wordCount: number): number {
  const averageWPM = 200;
  return Math.ceil(wordCount / averageWPM);
}

// Add proper CORS headers helper
function corsHeaders() {
  return {
    "Access-Control-Allow-Origin": "*",
    "Access-Control-Allow-Methods": "POST, OPTIONS",
    "Access-Control-Allow-Headers": "Content-Type",
  };
}

export async function OPTIONS() {
  return new NextResponse(null, {
    status: 204,
    headers: corsHeaders(),
  });
}

export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const { url } = body;

    if (!url) {
      return NextResponse.json(
        { error: "URL is required" },
        {
          status: 400,
          headers: corsHeaders(),
        }
      );
    }

    // Validate URL format
    try {
      new URL(url);
    } catch {
      return NextResponse.json(
        { error: "Invalid URL format" },
        {
          status: 400,
          headers: corsHeaders(),
        }
      );
    }

    console.log(`Processing URL: ${url}`);

    // Fetch the webpage with better error handling
    const response = await axios.get(url, {
      headers: {
        "User-Agent":
          "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36",
        Accept:
          "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
        "Accept-Language": "en-US,en;q=0.5",
        "Accept-Encoding": "gzip, deflate",
        Connection: "keep-alive",
      },
      timeout: 15000, // Increased timeout
      maxRedirects: 5,
    });

    const html = response.data;
    const $ = cheerio.load(html);

    // Extract title with better fallbacks
    const title =
      $("title").text().trim() ||
      $("h1").first().text().trim() ||
      $('meta[property="og:title"]').attr("content") ||
      "Untitled Article";

    // Extract main content
    const content = extractTextFromHtml(html);

    if (!content || content.length < 100) {
      return NextResponse.json(
        { error: "Could not extract sufficient content from the webpage" },
        {
          status: 400,
          headers: corsHeaders(),
        }
      );
    }

    // Generate summary
    const summary = generateSummary(content);

    if (!summary) {
      return NextResponse.json(
        { error: "Could not generate summary from the content" },
        {
          status: 400,
          headers: corsHeaders(),
        }
      );
    }

    // Translate to Urdu
    const urduSummary = translateToUrdu(summary);

    // Calculate metrics
    const wordCount = content.split(/\s+/).length;
    const readTime = calculateReadTime(wordCount);

    const processedBlog = {
      url,
      title: title.substring(0, 200), // Limit title length
      content: content.substring(0, 5000), // Limit content length for response
      summary,
      urduSummary,
      wordCount,
      readTime,
    };

    console.log(`Successfully processed: ${title}`);

    return NextResponse.json(processedBlog, {
      status: 200,
      headers: corsHeaders(),
    });
  } catch (error) {
    console.error("Error processing blog:", error);

    if (axios.isAxiosError(error)) {
      if (error.code === "ENOTFOUND" || error.code === "ECONNREFUSED") {
        return NextResponse.json(
          { error: "Could not connect to the website. Please check the URL." },
          {
            status: 400,
            headers: corsHeaders(),
          }
        );
      }

      if (error.response?.status === 404) {
        return NextResponse.json(
          { error: "The webpage was not found (404)." },
          {
            status: 400,
            headers: corsHeaders(),
          }
        );
      }

      if (error.response?.status === 403) {
        return NextResponse.json(
          {
            error:
              "Access forbidden. The website may be blocking automated requests.",
          },
          {
            status: 400,
            headers: corsHeaders(),
          }
        );
      }

      if (error.code === "ECONNABORTED") {
        return NextResponse.json(
          { error: "Request timeout. The website took too long to respond." },
          {
            status: 400,
            headers: corsHeaders(),
          }
        );
      }
    }

    return NextResponse.json(
      { error: "Failed to process the blog. Please try again." },
      {
        status: 500,
        headers: corsHeaders(),
      }
    );
  }
}

// Debug GET handler to verify route deployment
export async function GET() {
  return new Response("API route is working!", {
    status: 200,
    headers: corsHeaders(),
  });
}
